//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceLibros.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibreriaEntities2 : DbContext
    {
        public LibreriaEntities2()
            : base("name=LibreriaEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Libros> Libros { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
    
        public virtual ObjectResult<spObtener_Result> spObtener()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtener_Result>("spObtener");
        }
    }
}
